[build]
pre-build = [
  "curl -fsSL https://deb.nodesource.com/setup_16.x | DEBIAN_FRONTEND=noninteractive bash",  
  "DEBIAN_FRONTEND=noninteractive apt-get install -y nodejs"
]

[build.env]
passthrough = ["GRACO_HOME=/tmp"]