[package]
name = "depot-test-utils"
version = "0.1.0"
edition = "2021"
authors = ["Will Crichton <crichton.will@gmail.com>"]
publish = false

[dependencies]
snapbox = "0.4"
tempfile = "3.4"
shlex = "1"
either = "1"