name: 'Install Depot'
description: 'Installs the Depot binary and its dependencies.'
runs:
  using: "composite"
  steps:
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 24.11.0
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.21.0
    - name: Install Depot
      run: curl --silent https://raw.githubusercontent.com/cognitive-engineering-lab/depot/main/scripts/install.sh | sh
      shell: bash
    - name: Add Depot to PATH (non-Windows)
      if: runner.os != 'Windows'
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      shell: bash
    - name: Add Depot to PATH (Windows)
      if: runner.os == 'Windows'
      run: echo "$env:USERPROFILE\.local\bin" >> $env:GITHUB_PATH
      shell: pwsh
    - name: Confirm Depot is installed
      run: depot --version
      shell: bash