name: 'Install Depot'
description: 'Installs the Depot binary and its dependencies.'
runs:
  using: "composite"
  steps:
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 20.15.0
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9.13.2
    - name: Install Depot
      run: curl https://raw.githubusercontent.com/cognitive-engineering-lab/depot/main/scripts/install.sh | sh
      shell: bash